# coding: utf-8

"""
    Kancelaria API

    API for managing law firms and clients.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.kancelaria_update import KancelariaUpdate

class TestKancelariaUpdate(unittest.TestCase):
    """KancelariaUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KancelariaUpdate:
        """Test KancelariaUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KancelariaUpdate`
        """
        model = KancelariaUpdate()
        if include_optional:
            return KancelariaUpdate(
                name = 'Law Firm A',
                location = 'Warsaw, Poland',
                specialization = 'Criminal Law'
            )
        else:
            return KancelariaUpdate(
        )
        """

    def testKancelariaUpdate(self):
        """Test KancelariaUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
