# coding: utf-8

"""
    Kancelaria API

    API for managing law firms and clients.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.kancelarie_api import KancelarieApi


class TestKancelarieApi(unittest.TestCase):
    """KancelarieApi unit test stubs"""

    def setUp(self) -> None:
        self.api = KancelarieApi()

    def tearDown(self) -> None:
        pass

    def test_create_kancelaria(self) -> None:
        """Test case for create_kancelaria

        Create a new law firm
        """
        pass

    def test_delete_kancelaria(self) -> None:
        """Test case for delete_kancelaria

        Delete a law firm by ID
        """
        pass

    def test_read_kancelaria(self) -> None:
        """Test case for read_kancelaria

        Retrieve a specific law firm by ID
        """
        pass

    def test_read_kancelarie(self) -> None:
        """Test case for read_kancelarie

        Retrieve all law firms
        """
        pass

    def test_update_kancelaria(self) -> None:
        """Test case for update_kancelaria

        Update an existing law firm by ID
        """
        pass


if __name__ == '__main__':
    unittest.main()
