# coding: utf-8

"""
    Kancelaria API

    API for managing law firms and clients.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.users_api import UsersApi


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsersApi()

    def tearDown(self) -> None:
        pass

    def test_login_for_access_token(self) -> None:
        """Test case for login_for_access_token

        Authenticate user and get access token
        """
        pass

    def test_read_users_me(self) -> None:
        """Test case for read_users_me

        Get current user
        """
        pass

    def test_register_user(self) -> None:
        """Test case for register_user

        Register a new user
        """
        pass


if __name__ == '__main__':
    unittest.main()
