# coding: utf-8

"""
    Kancelaria API

    API for managing law firms and clients.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.user_base import UserBase

class TestUserBase(unittest.TestCase):
    """UserBase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserBase:
        """Test UserBase
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserBase`
        """
        model = UserBase()
        if include_optional:
            return UserBase(
                email = 'user@example.com'
            )
        else:
            return UserBase(
                email = 'user@example.com',
        )
        """

    def testUserBase(self):
        """Test UserBase"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
