# coding: utf-8

"""
    Kancelaria API

    API for managing law firms and clients.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.kancelaria_base import KancelariaBase

class TestKancelariaBase(unittest.TestCase):
    """KancelariaBase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KancelariaBase:
        """Test KancelariaBase
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KancelariaBase`
        """
        model = KancelariaBase()
        if include_optional:
            return KancelariaBase(
                name = 'Law Firm A',
                location = 'Warsaw, Poland',
                specialization = 'Criminal Law'
            )
        else:
            return KancelariaBase(
                name = 'Law Firm A',
                location = 'Warsaw, Poland',
                specialization = 'Criminal Law',
        )
        """

    def testKancelariaBase(self):
        """Test KancelariaBase"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
