/* tslint:disable */
/* eslint-disable */
/**
 * Kancelaria API
 * API for managing law firms and clients.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  KancelariaCreate,
  KancelariaInDB,
  KancelariaUpdate,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    KancelariaCreateFromJSON,
    KancelariaCreateToJSON,
    KancelariaInDBFromJSON,
    KancelariaInDBToJSON,
    KancelariaUpdateFromJSON,
    KancelariaUpdateToJSON,
} from '../models/index';

export interface CreateKancelariaRequest {
    kancelariaCreate: KancelariaCreate;
}

export interface DeleteKancelariaRequest {
    kancelariaId: number;
}

export interface ReadKancelariaRequest {
    kancelariaId: number;
}

export interface UpdateKancelariaRequest {
    kancelariaId: number;
    kancelariaUpdate: KancelariaUpdate;
}

/**
 * 
 */
export class KancelarieApi extends runtime.BaseAPI {

    /**
     * Create a new law firm
     */
    async createKancelariaRaw(requestParameters: CreateKancelariaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<KancelariaInDB>> {
        if (requestParameters['kancelariaCreate'] == null) {
            throw new runtime.RequiredError(
                'kancelariaCreate',
                'Required parameter "kancelariaCreate" was null or undefined when calling createKancelaria().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/kancelarie`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: KancelariaCreateToJSON(requestParameters['kancelariaCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => KancelariaInDBFromJSON(jsonValue));
    }

    /**
     * Create a new law firm
     */
    async createKancelaria(requestParameters: CreateKancelariaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KancelariaInDB> {
        const response = await this.createKancelariaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a law firm by ID
     */
    async deleteKancelariaRaw(requestParameters: DeleteKancelariaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['kancelariaId'] == null) {
            throw new runtime.RequiredError(
                'kancelariaId',
                'Required parameter "kancelariaId" was null or undefined when calling deleteKancelaria().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/kancelarie/{kancelaria_id}`;
        urlPath = urlPath.replace(`{${"kancelaria_id"}}`, encodeURIComponent(String(requestParameters['kancelariaId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a law firm by ID
     */
    async deleteKancelaria(requestParameters: DeleteKancelariaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteKancelariaRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieve a specific law firm by ID
     */
    async readKancelariaRaw(requestParameters: ReadKancelariaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<KancelariaInDB>> {
        if (requestParameters['kancelariaId'] == null) {
            throw new runtime.RequiredError(
                'kancelariaId',
                'Required parameter "kancelariaId" was null or undefined when calling readKancelaria().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/kancelarie/{kancelaria_id}`;
        urlPath = urlPath.replace(`{${"kancelaria_id"}}`, encodeURIComponent(String(requestParameters['kancelariaId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => KancelariaInDBFromJSON(jsonValue));
    }

    /**
     * Retrieve a specific law firm by ID
     */
    async readKancelaria(requestParameters: ReadKancelariaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KancelariaInDB> {
        const response = await this.readKancelariaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve all law firms
     */
    async readKancelarieRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<KancelariaInDB>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/kancelarie`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(KancelariaInDBFromJSON));
    }

    /**
     * Retrieve all law firms
     */
    async readKancelarie(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<KancelariaInDB>> {
        const response = await this.readKancelarieRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update an existing law firm by ID
     */
    async updateKancelariaRaw(requestParameters: UpdateKancelariaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<KancelariaInDB>> {
        if (requestParameters['kancelariaId'] == null) {
            throw new runtime.RequiredError(
                'kancelariaId',
                'Required parameter "kancelariaId" was null or undefined when calling updateKancelaria().'
            );
        }

        if (requestParameters['kancelariaUpdate'] == null) {
            throw new runtime.RequiredError(
                'kancelariaUpdate',
                'Required parameter "kancelariaUpdate" was null or undefined when calling updateKancelaria().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/kancelarie/{kancelaria_id}`;
        urlPath = urlPath.replace(`{${"kancelaria_id"}}`, encodeURIComponent(String(requestParameters['kancelariaId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: KancelariaUpdateToJSON(requestParameters['kancelariaUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => KancelariaInDBFromJSON(jsonValue));
    }

    /**
     * Update an existing law firm by ID
     */
    async updateKancelaria(requestParameters: UpdateKancelariaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KancelariaInDB> {
        const response = await this.updateKancelariaRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
