# coding: utf-8

# flake8: noqa

"""
    Kancelaria API

    API for managing law firms and clients.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "KancelarieApi",
    "UsersApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "HTTPValidationError",
    "KancelariaBase",
    "KancelariaCreate",
    "KancelariaInDB",
    "KancelariaUpdate",
    "Token",
    "TokenData",
    "UserBase",
    "UserCreate",
    "UserInDB",
    "ValidationError",
]

# import apis into sdk package
from openapi_client.api.kancelarie_api import KancelarieApi as KancelarieApi
from openapi_client.api.users_api import UsersApi as UsersApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.http_validation_error import HTTPValidationError as HTTPValidationError
from openapi_client.models.kancelaria_base import KancelariaBase as KancelariaBase
from openapi_client.models.kancelaria_create import KancelariaCreate as KancelariaCreate
from openapi_client.models.kancelaria_in_db import KancelariaInDB as KancelariaInDB
from openapi_client.models.kancelaria_update import KancelariaUpdate as KancelariaUpdate
from openapi_client.models.token import Token as Token
from openapi_client.models.token_data import TokenData as TokenData
from openapi_client.models.user_base import UserBase as UserBase
from openapi_client.models.user_create import UserCreate as UserCreate
from openapi_client.models.user_in_db import UserInDB as UserInDB
from openapi_client.models.validation_error import ValidationError as ValidationError
