"""Initial empty baseline migration

Revision ID: 0001_initial
Revises: 
Create Date: 2025-09-24

This baseline migration intentionally does not create any tables because
the application currently initializes schema via SQLAlchemy
(Base.metadata.create_all). Future migrations can build on top of this
baseline. If you prefer to manage schema exclusively via Alembic,
replace this migration with an autogenerated one and remove
Base.metadata.create_all from app/main.py.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Baseline migration: no-op
    pass


def downgrade() -> None:
    # Baseline migration: no-op
    pass
