/* tslint:disable */
/* eslint-disable */
/**
 * Kancelaria API
 * API for managing law firms and clients.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KancelariaInDB
 */
export interface KancelariaInDB {
    /**
     * 
     * @type {string}
     * @memberof KancelariaInDB
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof KancelariaInDB
     */
    location: string;
    /**
     * 
     * @type {string}
     * @memberof KancelariaInDB
     */
    specialization: string;
    /**
     * 
     * @type {number}
     * @memberof KancelariaInDB
     */
    id: number;
}

/**
 * Check if a given object implements the KancelariaInDB interface.
 */
export function instanceOfKancelariaInDB(value: object): value is KancelariaInDB {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('specialization' in value) || value['specialization'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function KancelariaInDBFromJSON(json: any): KancelariaInDB {
    return KancelariaInDBFromJSONTyped(json, false);
}

export function KancelariaInDBFromJSONTyped(json: any, ignoreDiscriminator: boolean): KancelariaInDB {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'location': json['location'],
        'specialization': json['specialization'],
        'id': json['id'],
    };
}

export function KancelariaInDBToJSON(json: any): KancelariaInDB {
    return KancelariaInDBToJSONTyped(json, false);
}

export function KancelariaInDBToJSONTyped(value?: KancelariaInDB | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'location': value['location'],
        'specialization': value['specialization'],
        'id': value['id'],
    };
}

