/* tslint:disable */
/* eslint-disable */
/**
 * Kancelaria API
 * API for managing law firms and clients.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KancelariaCreate
 */
export interface KancelariaCreate {
    /**
     * 
     * @type {string}
     * @memberof KancelariaCreate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof KancelariaCreate
     */
    location: string;
    /**
     * 
     * @type {string}
     * @memberof KancelariaCreate
     */
    specialization: string;
}

/**
 * Check if a given object implements the KancelariaCreate interface.
 */
export function instanceOfKancelariaCreate(value: object): value is KancelariaCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('specialization' in value) || value['specialization'] === undefined) return false;
    return true;
}

export function KancelariaCreateFromJSON(json: any): KancelariaCreate {
    return KancelariaCreateFromJSONTyped(json, false);
}

export function KancelariaCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): KancelariaCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'location': json['location'],
        'specialization': json['specialization'],
    };
}

export function KancelariaCreateToJSON(json: any): KancelariaCreate {
    return KancelariaCreateToJSONTyped(json, false);
}

export function KancelariaCreateToJSONTyped(value?: KancelariaCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'location': value['location'],
        'specialization': value['specialization'],
    };
}

