/* tslint:disable */
/* eslint-disable */
/**
 * Kancelaria API
 * API for managing law firms and clients.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KancelariaBase
 */
export interface KancelariaBase {
    /**
     * 
     * @type {string}
     * @memberof KancelariaBase
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof KancelariaBase
     */
    location: string;
    /**
     * 
     * @type {string}
     * @memberof KancelariaBase
     */
    specialization: string;
}

/**
 * Check if a given object implements the KancelariaBase interface.
 */
export function instanceOfKancelariaBase(value: object): value is KancelariaBase {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('specialization' in value) || value['specialization'] === undefined) return false;
    return true;
}

export function KancelariaBaseFromJSON(json: any): KancelariaBase {
    return KancelariaBaseFromJSONTyped(json, false);
}

export function KancelariaBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): KancelariaBase {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'location': json['location'],
        'specialization': json['specialization'],
    };
}

export function KancelariaBaseToJSON(json: any): KancelariaBase {
    return KancelariaBaseToJSONTyped(json, false);
}

export function KancelariaBaseToJSONTyped(value?: KancelariaBase | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'location': value['location'],
        'specialization': value['specialization'],
    };
}

