/* tslint:disable */
/* eslint-disable */
/**
 * Kancelaria API
 * API for managing law firms and clients.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KancelariaUpdate
 */
export interface KancelariaUpdate {
    /**
     * 
     * @type {string}
     * @memberof KancelariaUpdate
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof KancelariaUpdate
     */
    location?: string;
    /**
     * 
     * @type {string}
     * @memberof KancelariaUpdate
     */
    specialization?: string;
}

/**
 * Check if a given object implements the KancelariaUpdate interface.
 */
export function instanceOfKancelariaUpdate(value: object): value is KancelariaUpdate {
    return true;
}

export function KancelariaUpdateFromJSON(json: any): KancelariaUpdate {
    return KancelariaUpdateFromJSONTyped(json, false);
}

export function KancelariaUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): KancelariaUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'location': json['location'] == null ? undefined : json['location'],
        'specialization': json['specialization'] == null ? undefined : json['specialization'],
    };
}

export function KancelariaUpdateToJSON(json: any): KancelariaUpdate {
    return KancelariaUpdateToJSONTyped(json, false);
}

export function KancelariaUpdateToJSONTyped(value?: KancelariaUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'location': value['location'],
        'specialization': value['specialization'],
    };
}

