/* tslint:disable */
/* eslint-disable */
/**
 * Kancelaria API
 * API for managing law firms and clients.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenData
 */
export interface TokenData {
    /**
     * 
     * @type {string}
     * @memberof TokenData
     */
    email?: string;
}

/**
 * Check if a given object implements the TokenData interface.
 */
export function instanceOfTokenData(value: object): value is TokenData {
    return true;
}

export function TokenDataFromJSON(json: any): TokenData {
    return TokenDataFromJSONTyped(json, false);
}

export function TokenDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenData {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function TokenDataToJSON(json: any): TokenData {
    return TokenDataToJSONTyped(json, false);
}

export function TokenDataToJSONTyped(value?: TokenData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

