/* tslint:disable */
/* eslint-disable */
/**
 * Kancelaria API
 * API for managing law firms and clients.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserInDB
 */
export interface UserInDB {
    /**
     * 
     * @type {string}
     * @memberof UserInDB
     */
    email: string;
    /**
     * 
     * @type {number}
     * @memberof UserInDB
     */
    id: number;
    /**
     * 
     * @type {boolean}
     * @memberof UserInDB
     */
    isActive: boolean;
}

/**
 * Check if a given object implements the UserInDB interface.
 */
export function instanceOfUserInDB(value: object): value is UserInDB {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    return true;
}

export function UserInDBFromJSON(json: any): UserInDB {
    return UserInDBFromJSONTyped(json, false);
}

export function UserInDBFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInDB {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'id': json['id'],
        'isActive': json['is_active'],
    };
}

export function UserInDBToJSON(json: any): UserInDB {
    return UserInDBToJSONTyped(json, false);
}

export function UserInDBToJSONTyped(value?: UserInDB | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'id': value['id'],
        'is_active': value['isActive'],
    };
}

