/* tslint:disable */
/* eslint-disable */
/**
 * Kancelaria API
 * API for managing law firms and clients.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserBase
 */
export interface UserBase {
    /**
     * 
     * @type {string}
     * @memberof UserBase
     */
    email: string;
}

/**
 * Check if a given object implements the UserBase interface.
 */
export function instanceOfUserBase(value: object): value is UserBase {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function UserBaseFromJSON(json: any): UserBase {
    return UserBaseFromJSONTyped(json, false);
}

export function UserBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserBase {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function UserBaseToJSON(json: any): UserBase {
    return UserBaseToJSONTyped(json, false);
}

export function UserBaseToJSONTyped(value?: UserBase | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

