# coding: utf-8

# flake8: noqa
"""
    Kancelaria API

    API for managing law firms and clients.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.http_validation_error import HTTPValidationError
from openapi_client.models.kancelaria_base import KancelariaBase
from openapi_client.models.kancelaria_create import KancelariaCreate
from openapi_client.models.kancelaria_in_db import KancelariaInDB
from openapi_client.models.kancelaria_update import KancelariaUpdate
from openapi_client.models.token import Token
from openapi_client.models.token_data import TokenData
from openapi_client.models.user_base import UserBase
from openapi_client.models.user_create import UserCreate
from openapi_client.models.user_in_db import UserInDB
from openapi_client.models.validation_error import ValidationError
